name: main
on:
  push:
  pull_request:
    branches: [main]
jobs:
  tests:
    env:
      TEST_ES_SERVER: http://localhost:9200
      PORT: 9200
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Increase system limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
    - uses: elastic/elastic-github-actions/elasticsearch@master
      with:
        stack-version: 8.13.0-SNAPSHOT
        security-enabled: false
    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
    - name: Run tests
      run: crystal spec
